{{- if (include "featbit.mongodb.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "featbit.mongodb.secretName" . }}
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
type: Opaque
data:
  {{ include "featbit.mongodb.secretKey" . }}: {{ include "featbit.mongodb.connStr" . | b64enc | quote }}
{{- end }}