apiExternalUrl: "http://192.168.64.32:30050"
evaluationServerExternalUrl: "http://192.168.64.32:30100"

ui:
  service:
    type: NodePort

api:
  service:
    type: NodePort

els:
  service:
    type: NodePort