apiExternalUrl: ""
evaluationServerExternalUrl: ""
autoDiscovery: true

ui:
  service:
    type: LoadBalancer
    port: 80


api:
  service:
    type: LoadBalancer
    port: 80

els:
  service:
    type: LoadBalancer
    port: 80